export type AllocationSeed = {
  id: number;
  event: string;
  color: string;
  colorDetail?: string;
  bibConfirm: number;
  bibSign: number;
  rider: string;
  club: string;
  location: string;
  currentStatus: string;
  crawQty: number;
  lastEvent: string;
  remark: string;
  stockCode: string;
  stockColor: string;
  matchStatus: string;
};

export const cen80Bibs = [
  3, 12, 14, 26, 28, 40, 41, 42, 43, 45, 46, 48, 49, 50,
];

export const cen40Bibs = [
  1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
  25, 27, 29, 30, 32, 33, 34, 36, 38, 39, 44, 47,
];

const tefBibRows = [
  ...Array.from({ length: 20 }, (_, index) => 121 + index),
  ...Array.from({ length: 20 }, (_, index) => 201 + index),
];
const tefOrangeQuantity = (bib: number) => (bib === 208 ? 3 : 4);
const tefBibStock = tefBibRows.flatMap((bib) => [
  {
    code: `CEI_${bib}_WHITE`,
    event: bib >= 201 ? 'CEI 2*' : 'CEI 1*',
    color: 'White',
    bib,
    value: 500,
  },
  ...Array.from({ length: tefOrangeQuantity(bib) }, (_, index) => ({
    code: `CEI_${bib}_ORANGE_${index + 1}`,
    event: bib >= 201 ? 'CEI 2*' : 'CEI 1*',
    color: 'Orange',
    bib,
    value: 500,
  })),
]);

const tefOfficialStock = [
  ['J_BLUE001', 1],
  ['J_BLUE002', 5],
  ['J_BLUE003', 1],
  ['J_BLUE004', 1],
  ['J_BLUE005', 10],
  ['J_BLUE006', 1],
  ['J_BLUE007', 8],
  ['J_BLUE008', 10],
  ['J_BLUE009', 1],
  ['J_BLUE010', 8],
  ['J_BLUE011', 5],
  ['J_BLUE012', 5],
  ['J_BLUE013', 4],
  ['J_BLUE014', 5],
  ['J_BLUE015', 10],
].flatMap(([code, quantity]) =>
  Array.from({ length: Number(quantity) }, (_, index) => ({
    code: `${code}_${index + 1}`,
    event: 'Officials',
    color: 'Blue',
    bib: String(code),
    value: 500,
  })),
);

const tefPhotoStock = Array.from({ length: 5 }, (_, index) => ({
  code: `Photo_EN_${index + 1}`,
  event: 'Photo',
  color: 'Green khaki',
  bib: 'Photo_EN',
  value: 500,
}));

export const stockSeeds = [
  ...cen80Bibs.map((bib, index) => ({
    code: `TEF_EN_${String(index + 1).padStart(4, '0')}`,
    event: 'CEN 80 KM',
    color: 'Orange',
    bib,
    value: 500,
  })),
  ...cen40Bibs.map((bib, index) => ({
    code: `TEF_EN_${String(index + cen80Bibs.length + 1).padStart(4, '0')}`,
    event: 'CEN 40 KM',
    color: 'Lemon',
    bib,
    value: 500,
  })),
  ...tefBibStock,
  ...tefOfficialStock,
  ...tefPhotoStock,
];

export const allAllocationSeeds: AllocationSeed[] = [
  {
    id: 1,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 201,
    bibSign: 201,
    rider: "",
    club: "",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "CEI_201_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 2,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 202,
    bibSign: 202,
    rider: "",
    club: "",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "CEI_202_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 3,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 203,
    bibSign: 203,
    rider: "",
    club: "",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "CEI_203_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 4,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 204,
    bibSign: 204,
    rider: "",
    club: "",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "CEI_204_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 5,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 205,
    bibSign: 205,
    rider: "",
    club: "",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "CEI_205_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 6,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 206,
    bibSign: 206,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_206_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 7,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 207,
    bibSign: 207,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_207_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 8,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 208,
    bibSign: 208,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 4,
    lastEvent: "",
    remark: "ตัว สูญหาย1",
    stockCode: "CEI_208_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 9,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 209,
    bibSign: 209,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_209_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 10,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 210,
    bibSign: 210,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_210_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 11,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 211,
    bibSign: 211,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_211_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 12,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 212,
    bibSign: 212,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_212_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 13,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 213,
    bibSign: 213,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_213_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 14,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 214,
    bibSign: 214,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_214_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 15,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 215,
    bibSign: 215,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_215_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 16,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 216,
    bibSign: 216,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_216_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 17,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 217,
    bibSign: 217,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_217_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 18,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 218,
    bibSign: 218,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_218_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 19,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 219,
    bibSign: 219,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_219_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 20,
    event: "CEI 2*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 220,
    bibSign: 220,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_220_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 21,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 121,
    bibSign: 121,
    rider: "",
    club: "",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "CEI_121_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 22,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 122,
    bibSign: 122,
    rider: "",
    club: "",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "CEI_122_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 23,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 123,
    bibSign: 123,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_123_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 24,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 124,
    bibSign: 124,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_124_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 25,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 125,
    bibSign: 125,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_125_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 26,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 126,
    bibSign: 126,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_126_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 27,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 127,
    bibSign: 127,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_127_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 28,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 128,
    bibSign: 128,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_128_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 29,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 129,
    bibSign: 129,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_129_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 30,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 130,
    bibSign: 130,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_130_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 31,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 131,
    bibSign: 131,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_131_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 32,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 132,
    bibSign: 132,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_132_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 33,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 133,
    bibSign: 133,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_133_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 34,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 134,
    bibSign: 134,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_134_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 35,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 135,
    bibSign: 135,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_135_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 36,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 136,
    bibSign: 136,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_136_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 37,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 137,
    bibSign: 137,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_137_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 38,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 138,
    bibSign: 138,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_138_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 39,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 139,
    bibSign: 139,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_139_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 40,
    event: "CEI 1*",
    color: "White",
    colorDetail: "White (ขาว)",
    bibConfirm: 140,
    bibSign: 140,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "CEI_140_WHITE",
    stockColor: "White",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 41,
    event: "CEN 80",
    color: "Orange",
    colorDetail: "Orange (ส้ม)",
    bibConfirm: 3,
    bibSign: 3,
    rider: "พัชรพล บุญอยู่",
    club: "Gik Kor",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0001",
    stockColor: "Orange",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 42,
    event: "CEN 80",
    color: "Orange",
    colorDetail: "Orange (ส้ม)",
    bibConfirm: 12,
    bibSign: 12,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "TEF_EN_0002",
    stockColor: "Orange",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 43,
    event: "CEN 80",
    color: "Orange",
    colorDetail: "Orange (ส้ม)",
    bibConfirm: 14,
    bibSign: 14,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "TEF_EN_0003",
    stockColor: "Orange",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 44,
    event: "CEN 80",
    color: "Orange",
    colorDetail: "Orange (ส้ม)",
    bibConfirm: 26,
    bibSign: 26,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "TEF_EN_0004",
    stockColor: "Orange",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 45,
    event: "CEN 80",
    color: "Orange",
    colorDetail: "Orange (ส้ม)",
    bibConfirm: 28,
    bibSign: 28,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "TEF_EN_0005",
    stockColor: "Orange",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 46,
    event: "CEN 80",
    color: "Orange",
    colorDetail: "Orange (ส้ม)",
    bibConfirm: 40,
    bibSign: 40,
    rider: "อดิศร กล่ำเกลี้ยง",
    club: "Faro Farm+NSRC",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0006",
    stockColor: "Orange",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 47,
    event: "CEN 80",
    color: "Orange",
    colorDetail: "Orange (ส้ม)",
    bibConfirm: 41,
    bibSign: 41,
    rider: "เบญญาภา กรดเพ็ชร์",
    club: "Horseland",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0007",
    stockColor: "Orange",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 48,
    event: "CEN 80",
    color: "Orange",
    colorDetail: "Orange (ส้ม)",
    bibConfirm: 42,
    bibSign: 42,
    rider: "เพชรพราว ปานวิเชียร",
    club: "Suphan",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0008",
    stockColor: "Orange",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 49,
    event: "CEN 80",
    color: "Orange",
    colorDetail: "Orange (ส้ม)",
    bibConfirm: 43,
    bibSign: 43,
    rider: "จันทคุณ แสงสุขวาว",
    club: "Suphan",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0009",
    stockColor: "Orange",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 50,
    event: "CEN 80",
    color: "Orange",
    colorDetail: "Orange (ส้ม)",
    bibConfirm: 45,
    bibSign: 45,
    rider: "ณัฐณิชา ศิวทองกุล",
    club: "Chomtas",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0010",
    stockColor: "Orange",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 51,
    event: "CEN 80",
    color: "Orange",
    colorDetail: "Orange (ส้ม)",
    bibConfirm: 46,
    bibSign: 46,
    rider: "จันทวัฒน์ นาคะเลิศควี",
    club: "Suphan",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0011",
    stockColor: "Orange",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 52,
    event: "CEN 80",
    color: "Orange",
    colorDetail: "Orange (ส้ม)",
    bibConfirm: 48,
    bibSign: 48,
    rider: "",
    club: "",
    location: "Thai Polo",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0012",
    stockColor: "Orange",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 53,
    event: "CEN 80",
    color: "Orange",
    colorDetail: "Orange (ส้ม)",
    bibConfirm: 49,
    bibSign: 49,
    rider: "",
    club: "",
    location: "Thai Polo",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0013",
    stockColor: "Orange",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 54,
    event: "CEN 80",
    color: "Orange",
    colorDetail: "Orange (ส้ม)",
    bibConfirm: 50,
    bibSign: 50,
    rider: "",
    club: "",
    location: "Thai Polo",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0014",
    stockColor: "Orange",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 55,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 1,
    bibSign: 1,
    rider: "ชนิดาภา ทวีพัฒนะพงศ์",
    club: "Horsey",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0015",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 56,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 2,
    bibSign: 2,
    rider: "ธัญาดา ทวีพัฒนะพงศ์",
    club: "Horsey",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0016",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 57,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 4,
    bibSign: 4,
    rider: "ธนัท ปฏิบัติ",
    club: "Rayong",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0017",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 58,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 5,
    bibSign: 5,
    rider: "นลินนิภา มีศิลป์",
    club: "Gik Kor",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0018",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 59,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 6,
    bibSign: 6,
    rider: "ภูษิศา โบราณประสิทธิ์",
    club: "Horseland",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0019",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 60,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 7,
    bibSign: 7,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "TEF_EN_0020",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 61,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 8,
    bibSign: 8,
    rider: "เกสรา พิเสฐคุณาลัย",
    club: "Suphan",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0021",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 62,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 9,
    bibSign: 9,
    rider: "ธนัชคม พุทธารัก",
    club: "Horsey",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0022",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 63,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 10,
    bibSign: 10,
    rider: "",
    club: "",
    location: "TEF Office",
    currentStatus: "คงคลังตั้งต้น",
    crawQty: 5,
    lastEvent: "",
    remark: "",
    stockCode: "TEF_EN_0023",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 64,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 11,
    bibSign: 11,
    rider: "ณัฏฐ์รเดช จิตรภูเมืองปาน",
    club: "Horsey",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0024",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 65,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 13,
    bibSign: 13,
    rider: "เมลดา แนวโนนทัน",
    club: "Faro Farm+NSRC",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0025",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 66,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 15,
    bibSign: 15,
    rider: "ภาสินี วิลาสวรรณ",
    club: "Suphan",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0026",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 67,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 16,
    bibSign: 16,
    rider: "วิญญาภัทย์ จำปาเงิน",
    club: "Suphan",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0027",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 68,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 17,
    bibSign: 17,
    rider: "ณภัสนันท์ คนทน",
    club: "Suphan",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0028",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 69,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 18,
    bibSign: 18,
    rider: "กัลยกร บุญกิตติชัยพันธ์",
    club: "Mounted Police",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0029",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 70,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 19,
    bibSign: 19,
    rider: "กัลยาภรณ์ บุญกิตติชัยพันธ์",
    club: "Mounted Police",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0030",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 71,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 20,
    bibSign: 20,
    rider: "พิมพ์ลดา วรรณไพบูลย์",
    club: "Horsey",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0031",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 72,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 21,
    bibSign: 21,
    rider: "กษิต แวววงศ์",
    club: "Faro Farm+NSRC",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0032",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 73,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 22,
    bibSign: 22,
    rider: "พิมพ์กฤช แสนสุข",
    club: "Mcc",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0033",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 74,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 23,
    bibSign: 23,
    rider: "กษมา เกิดสว่าง",
    club: "Mcc",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0034",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 75,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 24,
    bibSign: 24,
    rider: "ขวัญศิชา ประมูลทอง",
    club: "Horseland",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0035",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 76,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 25,
    bibSign: 25,
    rider: "ฐิติวัฒน์ รัตนศรีงาม",
    club: "Horseland",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0036",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 77,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 27,
    bibSign: 27,
    rider: "พัชญพงษ์ วรรณไพบูลย์",
    club: "Horsey",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0037",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 78,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 29,
    bibSign: 29,
    rider: "พงศกร เหมะรัต",
    club: "Faro Farm+NSRC",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0038",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 79,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 30,
    bibSign: 30,
    rider: "ศิวกร สมบูรณ์",
    club: "Faro Farm+NSRC",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0039",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 80,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 32,
    bibSign: 32,
    rider: "ชนานันท์ นวลใย",
    club: "Chomtas",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0040",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 81,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 33,
    bibSign: 33,
    rider: "ธนิก กิจวินลัย",
    club: "Faro Farm+NSRC",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0041",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 82,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 34,
    bibSign: 34,
    rider: "ณัฐเศรษฐ เลียบเลียน",
    club: "Mcc",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0042",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 83,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 36,
    bibSign: 36,
    rider: "วุฒิณณ์ อุ่นคำ",
    club: "Mounted Police",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0043",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 84,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 38,
    bibSign: 38,
    rider: "นักรบ สุขสุศรี",
    club: "Faro Farm+NSRC",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0044",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 85,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 39,
    bibSign: 39,
    rider: "พีรดา วงศ์เวาประเสริฐ",
    club: "Horsey",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0045",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 86,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 44,
    bibSign: 44,
    rider: "ขวัญทิชา แก้วมีเงิน",
    club: "Faro Farm+NSRC",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0046",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
  {
    id: 87,
    event: "CEN 40",
    color: "Lemon",
    colorDetail: "Lemon (หรือ Green)",
    bibConfirm: 47,
    bibSign: 47,
    rider: "ณัฐเศรษฐ เจริญรื่น",
    club: "Gik Kor",
    location: "Thai Polo",
    currentStatus: "นำส่งซัก(ประสานพี่นิด Thai Polo",
    crawQty: 5,
    lastEvent: "DPE 2026",
    remark: "",
    stockCode: "TEF_EN_0047",
    stockColor: "Lemon",
    matchStatus: 'ตรงกับสต๊อกตั้งต้น',
  },
];

export const allocationSeeds = allAllocationSeeds;
